import os
import shutil
from datetime import datetime
from pathlib import Path

from sentence_transformers import InputExample, SentenceTransformer, losses
from torch.utils.data import DataLoader


BASE_MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"

MODELS_DIR = os.path.expanduser("~/Desktop/ml/volume/models")
BASE_MODEL_DIR = os.path.join(MODELS_DIR, "base_mpnet")
TMP_MODEL_DIR = os.path.join(MODELS_DIR, "base_mpnet_tmp")
BACKUP_PREFIX = "base_mpnet_old_"

BATCH_SIZE = 4
EPOCHS = 8
LR = 2e-5
WARMUP_STEPS = 0


DEMO_TRIPLETS = [
    InputExample(texts=[
        "c# backend",
        "asp.net backend developer",
        "react frontend developer"
    ]),
    InputExample(texts=[
        "c# backend",
        "asp.net core web api",
        "ui ux designer"
    ]),
    InputExample(texts=[
        "backend разработчик c#",
        "разработчик asp.net core",
        "ios swift developer"
    ]),
    InputExample(texts=[
        "dotnet backend",
        "asp.net microservices",
        "qa manual tester"
    ]),
    InputExample(texts=[
        "c# web api",
        "asp.net rest api",
        "android kotlin developer"
    ]),
    InputExample(texts=[
        "junior c# backend",
        "junior asp.net developer",
        "1c бухгалтер"
    ]),
    InputExample(texts=[
        "разработчик на c#",
        "asp.net engineer",
        "product manager"
    ]),
    InputExample(texts=[
        "backend .net",
        "asp.net core backend",
        "figma designer"
    ]),
    InputExample(texts=[
        "c# серверная разработка",
        "asp.net серверная разработка",
        "smm специалист"
    ]),
    InputExample(texts=[
        "c# api developer",
        "asp.net api developer",
        "hr manager"
    ]),
]


def deploy_model(model: SentenceTransformer) -> None:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    print("Saving trained model to temporary directory...")

    if os.path.exists(TMP_MODEL_DIR):
        shutil.rmtree(TMP_MODEL_DIR)

    model.save(TMP_MODEL_DIR)

    if os.path.exists(BASE_MODEL_DIR):
        backup_dir = os.path.join(MODELS_DIR, f"{BACKUP_PREFIX}{timestamp}")
        print(f"Backing up current model to: {backup_dir}")
        os.rename(BASE_MODEL_DIR, backup_dir)

    print("Promoting new demo model to base_mpnet...")
    os.rename(TMP_MODEL_DIR, BASE_MODEL_DIR)
    print("Demo model deployed.")


def train_demo_model() -> None:
    model_source = BASE_MODEL_DIR if os.path.exists(BASE_MODEL_DIR) else BASE_MODEL_NAME
    print(f"Loading model from: {model_source}")
    model = SentenceTransformer(model_source)

    train_loader = DataLoader(
        DEMO_TRIPLETS,
        shuffle=True,
        batch_size=BATCH_SIZE
    )

    train_loss = losses.TripletLoss(model)

    print(f"Triplets count: {len(DEMO_TRIPLETS)}")
    print(f"Batch size: {BATCH_SIZE}")
    print(f"Epochs: {EPOCHS}")
    print(f"Learning rate: {LR}")

    model.fit(
        train_objectives=[(train_loader, train_loss)],
        epochs=EPOCHS,
        optimizer_params={"lr": LR},
        warmup_steps=WARMUP_STEPS,
        use_amp=True,
        show_progress_bar=True
    )

    os.makedirs(MODELS_DIR, exist_ok=True)
    deploy_model(model)

    print("Done.")
    print("Important: indexed document vectors in Elasticsearch are NOT regenerated by this script.")
    print("To see the effect in search, restart the embeddings container and reindex vacancies/resumes.")


if __name__ == "__main__":
    Path(MODELS_DIR).mkdir(parents=True, exist_ok=True)
    train_demo_model()
