version: '3.8'

services:
  apigateway:
    build:
      context: .
      dockerfile: Services/ApiGateway/ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - authservice

    networks:
      - appnet