// <auto-generated />
using FilterService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FilterService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilterService.Models.Education", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Начальное общее образование"
                        },
                        new
                        {
                            id = 2,
                            name = "Основное общее образование"
                        },
                        new
                        {
                            id = 3,
                            name = "Среднее общее образование"
                        },
                        new
                        {
                            id = 4,
                            name = "Среднее профессиональное образование"
                        },
                        new
                        {
                            id = 5,
                            name = "Бакалавриат"
                        },
                        new
                        {
                            id = 6,
                            name = "Специалитет"
                        },
                        new
                        {
                            id = 7,
                            name = "Магистратура"
                        },
                        new
                        {
                            id = 8,
                            name = "Аспирантура"
                        },
                        new
                        {
                            id = 9,
                            name = "Ординатура"
                        });
                });

            modelBuilder.Entity("FilterService.Models.TypeOfActivity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("direction")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("direction", "type")
                        .HasDatabaseName("idx_direction_type");

                    b.ToTable("TypeOfActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
