// <auto-generated />
using System;
using CompanyService.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyService.DAL.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20260122075556_IntitialMig")]
    partial class IntitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyService.DAL.Entities.Company", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("website")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("company");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Deal", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Tarrifid")
                        .HasColumnType("integer");

                    b.Property<Guid?>("company_id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("date_end")
                        .HasColumnType("date");

                    b.Property<DateOnly>("date_start")
                        .HasColumnType("date");

                    b.Property<int>("sum")
                        .HasColumnType("integer");

                    b.Property<int>("tariff_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Tarrifid");

                    b.HasIndex("company_id");

                    b.HasIndex("tariff_id");

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Education", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("education");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Начальное общее образование"
                        },
                        new
                        {
                            id = 2,
                            name = "Основное общее образование"
                        },
                        new
                        {
                            id = 3,
                            name = "Среднее общее образование"
                        },
                        new
                        {
                            id = 4,
                            name = "Среднее профессиональное образование"
                        },
                        new
                        {
                            id = 5,
                            name = "Бакалавриат"
                        },
                        new
                        {
                            id = 6,
                            name = "Специалитет"
                        },
                        new
                        {
                            id = 7,
                            name = "Магистратура"
                        },
                        new
                        {
                            id = 8,
                            name = "Аспирантура"
                        },
                        new
                        {
                            id = 9,
                            name = "Ординатура"
                        });
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Tarrif", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("vacancy_count")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("tariff");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "Размещение 1 вакансии",
                            name = "Базовый",
                            price = 990,
                            vacancy_count = 1
                        },
                        new
                        {
                            id = 2,
                            description = "Размещение 3 вакансий",
                            name = "Стандартный",
                            price = 2990,
                            vacancy_count = 3
                        },
                        new
                        {
                            id = 3,
                            description = "Размещение 5 вакансий",
                            name = "Продвинутый",
                            price = 5990,
                            vacancy_count = 5
                        },
                        new
                        {
                            id = 4,
                            description = "Размещение 10 вакансий",
                            name = "Премиум",
                            price = 9990,
                            vacancy_count = 10
                        },
                        new
                        {
                            id = 5,
                            description = "Безлимитное размещение вакансий",
                            name = "Безлимитный",
                            price = 20000,
                            vacancy_count = 2147483647
                        });
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("company_id")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("education_id")
                        .HasColumnType("integer");

                    b.Property<int>("experience")
                        .HasColumnType("integer");

                    b.Property<DateTime>("income_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("max_salary")
                        .HasColumnType("integer");

                    b.Property<int>("min_salary")
                        .HasColumnType("integer");

                    b.Property<string>("post")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("work_format")
                        .HasColumnType("integer");

                    b.Property<int?>("work_hour")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("company_id");

                    b.HasIndex("education_id");

                    b.ToTable("vacancy");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Vacancy_filter", b =>
                {
                    b.Property<Guid>("filter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("typeOfActivity_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("vacancy_id")
                        .HasColumnType("uuid");

                    b.HasKey("filter_id");

                    b.HasIndex("vacancy_id", "typeOfActivity_id")
                        .IsUnique();

                    b.ToTable("vacancy_filter");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Deal", b =>
                {
                    b.HasOne("CompanyService.DAL.Entities.Tarrif", null)
                        .WithMany("Deals")
                        .HasForeignKey("Tarrifid");

                    b.HasOne("CompanyService.DAL.Entities.Company", "company")
                        .WithMany("Deals")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CompanyService.DAL.Entities.Tarrif", "tariff")
                        .WithMany()
                        .HasForeignKey("tariff_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("company");

                    b.Navigation("tariff");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Vacancy", b =>
                {
                    b.HasOne("CompanyService.DAL.Entities.Company", "company")
                        .WithMany("Vacancies")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyService.DAL.Entities.Education", "education")
                        .WithMany("vacancies")
                        .HasForeignKey("education_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("company");

                    b.Navigation("education");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Vacancy_filter", b =>
                {
                    b.HasOne("CompanyService.DAL.Entities.Vacancy", "vacancy")
                        .WithMany("Vacancy_filters")
                        .HasForeignKey("vacancy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vacancy");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Company", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Education", b =>
                {
                    b.Navigation("vacancies");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Tarrif", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("CompanyService.DAL.Entities.Vacancy", b =>
                {
                    b.Navigation("Vacancy_filters");
                });
#pragma warning restore 612, 618
        }
    }
}
