name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: |
          dotnet test Services/CompanyService/CompanyService.Tests \
            --no-build \
            --results-directory ./TestResults \
            --logger "trx;LogFileName=test-results.trx" \
            --collect:"XPlat Code Coverage"

      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:TestResults/**/coverage.cobertura.xml \
            -targetdir:coveragereport \
            -reporttypes:Html

#      - name: Install Allure
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y default-jre
#
#          ALLURE_VERSION=2.38.1
#
#          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz
#          tar -zxvf allure-${ALLURE_VERSION}.tgz
#
#          sudo mv allure-${ALLURE_VERSION} /opt/allure
#          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
#
#      - name: Generate Allure report
#        run: |
#          if [ -d "allure-results" ]; then
#            allure generate allure-results --clean -o allure-report
#          else
#            echo "No allure-results directory found, skipping Allure report"
#          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/**/*.trx

      - name: Upload coverage raw
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: TestResults/**/coverage.cobertura.xml

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coveragereport

#      - name: Upload Allure report
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-report
#          path: allure-report


  integration:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run integration tests
        run: |
          dotnet test Services/CompanyService/CompanyService.Tests \
            --filter "Category=Integration"


  report:
    runs-on: ubuntu-latest
    needs: [test, integration]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Show files
        run: ls -R